---
title: "DESeq2 All"
output:
html_notebook: default
---

```{r}
library(DESeq2)
library(ggplot2)
library(RColorBrewer)
library(circlize)
library(ComplexHeatmap)
options(scipen = 100)
```

```{bash}
ls
```

```{r}
Counts = read.delim("./output/rawCountsDESeq.csv", header = TRUE, row.names = 1, sep = ",")
```

```{r}
Counts
```

```{r}
newOrder = sort(colnames(Counts))
Counts <- Counts[, newOrder]
Counts
```


```{r}
Counts <- Counts[which(rowSums(Counts) > 50),]
# Counts = Counts+1
Counts
```

```{r}
# condition <- factor(c("C", "C", "C", "D", "D"))

condition = c()
for (value in colnames(Counts)) {
    firstValues = as.vector(strsplit(value, '[_]'))
    clusterStrings = firstValues[[1]][1]
    condition <- append(condition, substr(clusterStrings,1,1))
}

condition = factor(condition)
condition
```

```{r}
coldata <- data.frame(row.names = colnames(Counts), condition)
coldata
```

```{r}
fullColData <- coldata
fullCounts <- Counts

i = 0

dds = DESeqDataSetFromMatrix(countData = Counts, colData = coldata, design = ~condition)
dds = DESeq(dds)
res = results(dds, contrast = c("condition", "D", "C"))

sigs = na.omit(res)
sigs = sigs[sigs$padj < 0.05,]

df = as.data.frame(sigs)

df.top = df[(df$padj < 0.05) & (df$baseMean > 50) & (abs(df$log2FoldChange) > 2),]

df.top = df.top[order(df.top$log2FoldChange, decreasing = TRUE),]

df.top["symbol"] = row.names(df.top)

rlog_out <- vst(dds, blind=FALSE) #get normalized count data from dds object
mat<-assay(rlog_out)[rownames(df.top), rownames(coldata)] #sig genes x samples
print(is.null(mat))
print(dim(mat))

colnames(mat) <- rownames(coldata)
base_mean <- rowMeans(mat)
mat.scaled <- t(apply(mat, 1, scale)) #center and scale each column (Z-score) then transpose
colnames(mat.scaled)<-colnames(mat)

num_keep <- 25
keepRow <- 1:nrow(mat.scaled)
rows_keep = c(head(keepRow, num_keep), tail(keepRow, num_keep))

l2_val <- as.matrix(df.top[rows_keep,]$log2FoldChange) #getting log2 value for each gene we are keeping
colnames(l2_val)<-"logFC"
mean <- as.matrix(df.top[rows_keep,]$baseMean) #getting mean value for each gene we are keeping
colnames(mean)<-"AveExpr"

#maps values between b/w/r for min and max l2 values
col_logFC <- colorRamp2(c(min(l2_val),0, max(l2_val)), c("blue", "white", "red")) 
#maps between 0% quantile, and 75% quantile of mean values --- 0, 25, 50, 75, 100
col_AveExpr <- colorRamp2(c(quantile(mean)[1], quantile(mean)[4]), c("white", "red"))

ha <- HeatmapAnnotation(summary = anno_summary(gp = gpar(fill = 2), height = unit(2, "cm")))
h1 <- Heatmap(mat.scaled[rows_keep,], cluster_rows = F, 
            column_labels = colnames(mat.scaled), name="Z-score",
            cluster_columns = F)
h2 <- Heatmap(l2_val, row_labels = df.top$symbol[rows_keep], 
            cluster_rows = F, name="logFC", top_annotation = ha, col = col_logFC,
            cell_fun = function(j, i, x, y, w, h, col) { # add text to each grid
              grid.text(round(l2_val[i, j],2), x, y)
            })
h3 <- Heatmap(mean, row_labels = df.top$symbol[rows_keep], 
            cluster_rows = F, name = "AveExpr", col=col_AveExpr,
            cell_fun = function(j, i, x, y, w, h, col) { # add text to each grid
              grid.text(round(mean[i, j],2), x, y)
            })
h<-h1+h2+h3
h

fileOutputPDF = "./outputPDFs/DiffExpOut/HeatmapAllGenes.pdf"
fileOutputCSV = "./outputPDFs/DiffExpOut/HeatmapAll Genes.csv"

pdf(file = fileOutputPDF, width = 30, height = 10)
print(h)
dev.off()

write.csv(df.top,fileOutputCSV)

```





