---
title: "DESeq2 DiffExp"
output:
html_notebook: default
---

```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("DESeq2", force = TRUE)
```

```{r}
library(DESeq2)
library(ggplot2)
library(RColorBrewer)
library(circlize)
library(ComplexHeatmap)
options(scipen = 100)
```

```{bash}
ls
```

```{r}
Counts = read.delim("./output/rawCountsDESeqPerClusterNew.csv", header = TRUE, row.names = 1, sep = ",")
```

```{r}
Counts
```
```{r}
newOrder = sort(colnames(Counts))
Counts <- Counts[, newOrder]
Counts
```


```{r}
Counts <- Counts[which(rowSums(Counts) > 50),]
Counts = Counts+1
Counts
```

```{r}
# condition <- factor(c("C", "C", "C", "D", "D"))

condition = c()
for (value in colnames(Counts)) {
    firstValues = as.vector(strsplit(value, '[.]'))
    clusterStrings = firstValues[[1]][2]
    condition <- append(condition, substr(clusterStrings,1,1))
}

condition = factor(condition)
condition
```

```{r}
# condition <- factor(c("C", "C", "C", "D", "D"))

n_last <- 1  
clusters = c()

for (value in colnames(Counts)) {
    clusterList = as.vector(strsplit(value, '[.]'))
    clusterString = clusterList[[1]][1]
    firstChr = substr(clusterString, 1, 1)
    lastChr = substr(clusterString, nchar(clusterString) - n_last + 1, nchar(clusterString))
    clusterID = paste(firstChr, lastChr, sep="")
    clusters <- append(clusters, clusterID)
}

clusters = factor(clusters)
clusters
```

```{r}
coldata <- data.frame(row.names = colnames(Counts), condition, clusters)
coldata
```

```{r}
fullColData <- coldata
fullCounts <- Counts

i = 0

while(nrow(fullColData) >= 5){
  print(nrow(fullColData))
  coldata = head(fullColData, 5)
  Counts = fullCounts[,1:5]

  clusterID = substr(coldata[1, 2][1], 1, 2)
  print(clusterID)
  dds = DESeqDataSetFromMatrix(countData = Counts, colData = coldata, design = ~condition)
  dds = DESeq(dds)
  res = results(dds, contrast = c("condition", "D", "C"))
  
  if(i==0){
    ntd = normTransform(dds)
    m1 = assay(ntd)
    m2 = m1 - apply(m1, 1, mean)
    finalExpression = m2
  }
  else{
    ntd = normTransform(dds)
    m1 = assay(ntd)
    m2 = m1 - apply(m1, 1, mean)
    finalExpression = cbind(finalExpression, m2)
  }
  
  
  fullColData = fullColData[-1:-5, ]
  fullCounts = fullCounts[,-1:-5]
  i = i+1
  remove(list=c("ntd", "m1", "m2", "dds"))
}
```


```{r}
finalExpression
```



