---
title: "DESeq2 DiffExp"
output:
html_notebook: default
---

```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("DESeq2", force = TRUE)
```


```{r}
library(DESeq2)
library(ggplot2)
library(RColorBrewer)
library(circlize)
library(ComplexHeatmap)
library(pheatmap)
options(scipen = 100)
```

```{r}
Counts = read.delim("./output/rawCountsDESeqPerClusterNew.csv", header = TRUE, row.names = 1, sep = ",")
```

```{r}
Counts
```
```{r}
newOrder = sort(colnames(Counts))
Counts <- Counts[, newOrder]
Counts
```


```{r}
Counts <- Counts[which(rowSums(Counts) > 50),]
Counts = Counts+1
Counts
```

```{r}
# condition <- factor(c("C", "C", "C", "D", "D"))

condition = c()
for (value in colnames(Counts)) {
    firstValues = as.vector(strsplit(value, '[.]'))
    clusterStrings = firstValues[[1]][2]
    condition <- append(condition, substr(clusterStrings,1,1))
}

condition = factor(condition)
condition
```

```{r}
# condition <- factor(c("C", "C", "C", "D", "D"))

n_last <- 1  
clusters = c()

for (value in colnames(Counts)) {
    clusterList = as.vector(strsplit(value, '[.]'))
    clusterString = clusterList[[1]][1]
    firstChr = substr(clusterString, 1, 1)
    lastChr = substr(clusterString, nchar(clusterString) - n_last + 1, nchar(clusterString))
    clusterID = paste(firstChr, lastChr, sep="")
    clusters <- append(clusters, clusterID)
}

clusters = factor(clusters)
clusters
```

```{r}
coldata <- data.frame(row.names = colnames(Counts), condition, clusters)
coldata
```
```{r}
coldata$conditionCluster <- paste(coldata$condition, coldata$clusters, sep="_")
coldata
```

```{r}
dds = DESeqDataSetFromMatrix(countData = Counts, colData = coldata, design = ~conditionCluster)
dds = DESeq(dds)
```


```{r}
ntd = normTransform(dds)
m1 = assay(ntd)
m2 = m1 - apply(m1, 1, mean)
```


```{r}
m2DataFrame <- as.data.frame(m2)
options(scipen = 100)
m2DataFrameCON <- data.frame(row.names = rownames(m2DataFrame))
m2DataFrameDS <- data.frame(row.names = rownames(m2DataFrame))
for (i in colnames(m2DataFrame)){
  columnName = colnames(m2DataFrame[i])
  splitDot = as.vector(strsplit(columnName, '[.]'))[[1]][2]
  if(substr(splitDot,1,1) == "C"){
    m2DataFrameCON[columnName] = m2DataFrame[i]
  }
  else if (substr(splitDot,1,1) == "D"){
    m2DataFrameDS[columnName] = m2DataFrame[i]
  }
}
print("New Operation")
m2DataFrame

m2DataFrameCON
m2DataFrameDS
BY <- 3
m2AvgDataFrameCON = as.data.frame(sapply(1:(ncol(m2DataFrameCON)/BY), function(x) rowMeans(m2DataFrameCON[, ((x * BY) - BY + 1):(x * BY)])))
BY <- 2
m2AvgDataFrameDS = as.data.frame(sapply(1:(ncol(m2DataFrameDS)/BY), function(x) rowMeans(m2DataFrameDS[, ((x * BY) - BY + 1):(x * BY)])))
m2AvgDataDSvsCON = m2AvgDataFrameDS - m2AvgDataFrameCON

columnNamesAll = c()
for (i in colnames(m2DataFrameDS)){
  splitDot = as.vector(strsplit(i, '[.]'))[[1]][1]
  if(!(splitDot %in% columnNamesAll)){
    columnNamesAll = append(columnNamesAll, splitDot)
  }
}
print(columnNamesAll)
colnames(m2AvgDataFrameCON) <- columnNamesAll
colnames(m2AvgDataFrameDS) <- columnNamesAll
colnames(m2AvgDataDSvsCON) <- columnNamesAll
m2AvgDataFrameCON
m2AvgDataFrameDS
m2AvgDataDSvsCON
```
```{r}
clusts = unique(coldata$conditionCluster)
clusts
```

```{r}
# dds_res1 = as.data.frame(results(dds, contrast=c("conditionCluster", "C_IC", "D_IC")))
res = results(dds)
sigs = na.omit(res)
sigs = sigs[sigs$padj < 0.05,]
df = as.data.frame(sigs)
df.top = df[(df$padj < 0.05) & (abs(df$log2FoldChange) > 0.3),]
df.top
rownames(df.top)
```

```{r}
plot_heatmap = function(mat, genes = rownames(mat), 
                        cluster_cols = FALSE, 
                        cluster_rows = FALSE, 
                        color = viridis_pal(option = "viridis")(250), 
                        treeheight_row = 0, 
                        annotation_names_row = FALSE, 
                        breaks = seq(-5, 5, length.out = 250),
                        filename = "specifyFilename.pdf", 
                        width=15, 
                        height=7
                        ){
  
  m2 = mat[match(genes, rownames(mat), nomatch = 0),]
  
  pl1 = pheatmap(m2, show_rownames=TRUE, 
                 cluster_cols = cluster_cols, 
                 cluster_rows = cluster_rows, 
                 color = color, 
                 treeheight_row = treeheight_row, 
                 annotation_names_row = annotation_names_row, 
                 breaks = breaks
  )
  
  stopifnot(!missing(pl1))
  stopifnot(!missing(filename))
  pdf(filename, width=width, height=height)
  grid::grid.newpage()
  grid::grid.draw(pl1$gtable) # print(pl1) 
  dev.off()
  
  return(pl1)
  
}
```

```{r}
library(viridis)
allHeatMap = plot_heatmap(m2, genes= rownames(df.top), cluster_rows = TRUE, cluster_cols = TRUE, filename = "./outputPDFs/DiffExpOut/allDatasetPheatmap.pdf")
```


```{r}
pl_genes_clust =allHeatMap$tree_row$labels[allHeatMap$tree_row$order]
```


```{r}
CONHeatMap = plot_heatmap(m2, genes = c("CHCHD2", "RPS4Y1"), cluster_rows = FALSE, 
                          filename = "./outputPDFs/DiffExpOut/TEST.pdf", 
                          width=5,
                          height=7
                          )
```


```{r}
normGroupControlMatrix <- data.matrix(m2AvgDataFrameCON)
CONHeatMap = plot_heatmap(normGroupControlMatrix, genes = pl_genes_clust, cluster_rows = FALSE, 
                          filename = "./outputPDFs/DiffExpOut/PheatmapCONTROL.pdf", 
                          width=5,
                          height=7
                          )
```

```{r}
normGroupDownlMatrix <- data.matrix(m2AvgDataFrameDS)
DOWNHeatMap = plot_heatmap(normGroupDownlMatrix, genes = pl_genes_clust, cluster_rows = FALSE, 
                           filename = "./outputPDFs/DiffExpOut/PheatmapDOWN.pdf", 
                           width=5,
                           height=7
                           )
```

```{r}
normGroupVS <- data.matrix(m2AvgDataDSvsCON)
VSHeatMap = plot_heatmap(normGroupVS, genes = pl_genes_clust, cluster_rows = FALSE, 
                          filename = "./outputPDFs/DiffExpOut/PheatmapVS.pdf", 
                          color=colorRampPalette(c("magenta", "black", "yellow"))(50),
                          breaks = seq(-2, 2, length.out = 50),
                          width=5,
                          height=7
                          )
```



```{r}
# library(pheatmap)
# library(viridis)
# plotNorm = pheatmap::pheatmap(m2, cluster_cols = FALSE, color = viridis_pal(option = "viridis")(250), treeheight_row = 0, annotation_names_row = FALSE, breaks = seq(-5, 5, length.out = 250))
# 
# save_pheatmap_pdf <- function(x, filename, width=15, height=7) {
#    stopifnot(!missing(x))
#    stopifnot(!missing(filename))
#    pdf(filename, width=width, height=height)
#    grid::grid.newpage()
#    grid::grid.draw(x$gtable)
#    dev.off()
# }
# save_pheatmap_pdf(plotNorm, "./outputPDFs/DiffExpOut/FullDatasetPheatmapClusterColOFF.pdf")
```

```{r}
# normGroupControl <- read.csv("./output/NormAvgCountsCONTROL.csv")
# rownames(normGroupControl) <- normGroupControl$X
# normGroupControl <- normGroupControl[,-1]
# normGroupControlMatrix <- data.matrix(m2AvgDataFrameCON)
# 
# pl1 = pheatmap::pheatmap(normGroupControlMatrix, cluster_cols = FALSE, cluster_rows = TRUE, color = viridis_pal(option = "viridis")(250), treeheight_row = 0, annotation_names_row = FALSE, breaks = seq(-5, 5, length.out = 250))
# 
# save_pheatmap_pdf <- function(x, filename, width=5, height=7) {
#    stopifnot(!missing(x))
#    stopifnot(!missing(filename))
#    pdf(filename, width=width, height=height)
#    grid::grid.newpage()
#    grid::grid.draw(x$gtable)
#    dev.off()
# }
# save_pheatmap_pdf(pl1, "./outputPDFs/DiffExpOut/normGroupedControlPheatmap.pdf")
```

```{r}
# matGroupDown <- read.csv("./output/NormAvgCountsDOWN.csv")
# rownames(matGroupDown) <- matGroupDown$X
# matGroupDown <- matGroupDown[,-1]
# matGroupDownMatrix <- data.matrix(m2AvgDataFrameDS)
# 
# pl1 = pheatmap::pheatmap(matGroupDownMatrix, cluster_cols = FALSE, cluster_rows = TRUE, color = viridis_pal(option = "viridis")(250), treeheight_row = 0, annotation_names_row = FALSE, breaks = seq(-5, 5, length.out = 250))
# 
# save_pheatmap_pdf <- function(x, filename, width=5, height=7) {
#    stopifnot(!missing(x))
#    stopifnot(!missing(filename))
#    pdf(filename, width=width, height=height)
#    grid::grid.newpage()
#    grid::grid.draw(x$gtable)
#    dev.off()
# }
# save_pheatmap_pdf(pl1, "./outputPDFs/DiffExpOut/normGroupedDownPheatmap.pdf")
```

```{r}
# normGroupVS <- read.csv("./output/NormDiffCountsCONvsDS.csv")
# rownames(normGroupVS) <- normGroupVS$X
# normGroupVS <- normGroupVS[,-1]
# normGroupVSMatrix <- data.matrix(m2AvgDataDSvsCON)
# 
# pl2 = pheatmap::pheatmap(normGroupVSMatrix, cluster_cols = FALSE, cluster_rows = TRUE, color=colorRampPalette(c("yellow", "black", "magenta"))(50), treeheight_row = 0, annotation_names_row = FALSE, breaks = seq(-2, 2, length.out = 50))
# 
# save_pheatmap_pdf <- function(x, filename, width=5, height=7) {
#    stopifnot(!missing(x))
#    stopifnot(!missing(filename))
#    pdf(filename, width=width, height=height)
#    grid::grid.newpage()
#    grid::grid.draw(x$gtable)
#    dev.off()
# }
# save_pheatmap_pdf(pl2, "./outputPDFs/DiffExpOut/normVSPheatmap.pdf")
```
