---
title: "R Notebook"
output:
html_notebook: default
---

```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("clusterProfiler")
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("AnnotationDbi")
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("org.Hs.eg.db")
```

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationDbi)
```

```{r}
genesToKeep <- read.csv(file = './geneOrderDifference.csv')$x
genesToKeep
```


```{r}
expressionMatrix <- read.csv(file = './geneOrderDataframe.csv')
rownames(expressionMatrix) = expressionMatrix$X
expressionMatrix = expressionMatrix[expressionMatrix$X %in% genesToKeep, ]
expressionMatrix = expressionMatrix[ , !(names(expressionMatrix) %in% c("X"))]
expressionMatrix
```
```{r}
expressionMatrix$avg = rowMeans(expressionMatrix)
expressionMatrix <- expressionMatrix[order(expressionMatrix$avg),]
expressionMatrix
```
```{r}
positiveGenes = rownames(expressionMatrix[expressionMatrix$avg >= 0,])
positiveGenes
negativeGenes = rownames(expressionMatrix[expressionMatrix$avg <= 0,])
negativeGenes
```

```{r}
# NegativeGenes Genes
GO_results <- enrichGO(gene = negativeGenes, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
print(GO_results)
negativeResults = as.data.frame(GO_results)
negativeResults
```

```{r}
# PositiveGenes Genes
GO_results <- enrichGO(gene = positiveGenes, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
print(GO_results)
positiveResults = as.data.frame(GO_results)
positiveResults
```


